# Generated by Django 4.2.11 on 2026-03-19 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('access_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_professionals', models.ManyToManyField(blank=True, related_name='assigned_cases', to='professionals.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CASE_CREATED', 'Case Created'), ('EVIDENCE_ADDED', 'Evidence Added'), ('PROFESSIONAL_ASSIGNED', 'Professional Assigned'), ('STATUS_CHANGED', 'Status Changed')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='cases.case')),
            ],
        ),
    ]
